services:
  postgres:
    image: timescale/timescaledb-postgis:2.2.1-pg13
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      timeout: 10s
      interval: 30s
      retries: 5
      start_period: 15s
    environment:
      - POSTGRES_PASSWORD=p455w0rdD3v3l0p
    volumes:
      - postgres-data:/home/postgres/pgdata/data:z
    networks:
      default:
        aliases:
          - postgres
    logging:
      driver: "json-file"
      options:
        max-size: "50M"
        max-file: "18"

  mongo-db:
    image: mongo:3.6
    container_name: impetus-fiware-mongo
    ports:
      - "27017:27017" 
    command: --bind_ip_all --smallfiles
    volumes:
      - mongo-db:/data/db
    logging:
      driver: "json-file"
      options:
        max-size: "20M"
        max-file: "2"
    networks:
      default:
        aliases:
          - mongodb
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/test --quiet
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s

  fiware-orion:
    image: fiware/orion-ld:1.1.2
    container_name: impetus-fiware-orion
    ports:
      - "1026:1026"
    environment:
      - ORIONLD_TROE=FALSE
      - ORIONLD_TROE_USER=orion
      - ORIONLD_TROE_PWD=Str0ngPassw0rd
      - ORIONLD_TROE_HOST=impetus-timescale
      - ORIONLD_MONGO_HOST=mongo-db
    links:
      - mongo-db
    networks:
      default:
        aliases:
          - orion
    depends_on:
      mongo-db:
        condition: service_healthy
    command: -dbhost mongodb -logLevel DEBUG
    healthcheck:
      test: curl --fail -s http://impetus-orion:1026/version || exit 1
    logging:
      driver: "json-file"
      options:
        max-size: "20M"
        max-file: "2"
  # quantumleap:
  #   container_name: impetus-fiware-quantumleap
  #   image: orchestracities/quantumleap:edge
  #   # image: ods/quantumleap
  #   ports:
  #     - "8668:8668"
  #   environment:      
  #     - POSTGRES_HOST=postgres
  #     - POSTGRES_PORT=5432
  #     - POSTGRES_DB_NAME=quantumleap
  #     - POSTGRES_DB_USER=postgres
  #     - POSTGRES_DB_PASS=p455w0rdD3v3l0p
  #     - QL_CONFIG=/quantumleap.yaml
  #   networks:
  #     default:
  #       aliases:
  #         - quantumleap
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "20M"
  #       max-file: "2"
  #   volumes:
  #     - ./quantum.yaml:/quantumleap.yaml
  
  platform:
    build: 
      context: ./AccessModule/
      dockerfile: ./docker/Dockerfile
    container_name: impetus-accessmodule
    develop:
      watch: 
        - path: ./AccessModule/src
          action: rebuild
    environment:
      - PG_USERNAME=postgres
      - PG_PASSWORD=p455w0rdD3v3l0p
      - PG_HOSTNAME=postgres
      - PG_PORT=5432
      - PG_DATABASE=postgres
      - ORION_URL=http://orion:1026
      - FIWARE_FILES_PATH=/app/files
      - FIWARE_CONTEXT_PATH=/app/context
      - HOSTNAME=http://84.88.76.44
    volumes:
      - files:/app/files
      - context:/app/context
    ports:
      - "8000:80"
    networks:
      default:
        aliases:
          - accessmodule
    logging:
      driver: "json-file"
      options:
        max-size: "50M"
        max-file: "18"
    depends_on:
      fiware-orion:
        condition: service_healthy
volumes:
  mongo-db:
  crate-data:
  files:
  context:
  postgres-data: