services:
  mongo-db:
    image: mongo:3.6
    container_name: impetus-fiware-mongo
    ports:
      - "27017:27017" 
    command: --bind_ip_all --smallfiles
    volumes:
      - mongo-db:/data/db
    logging:
      driver: "json-file"
      options:
        max-size: "20M"
        max-file: "2"
    networks:
      default:
        aliases:
          - mongodb
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/test --quiet
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s

  fiware-orion:
    image: fiware/orion-ld:1.1.2
    container_name: impetus-fiware-orion
    ports:
      - "1026:1026"
    environment:
      - ORIONLD_TROE=FALSE
      - ORIONLD_TROE_USER=orion
      - ORIONLD_TROE_PWD=${ORION}
      - ORIONLD_TROE_HOST=impetus-timescale
      - ORIONLD_MONGO_HOST=mongo-db
    links:
      - mongo-db
    networks:
      default:
        aliases:
          - orion
    depends_on:
      mongo-db:
        condition: service_healthy
    command: -dbhost mongodb -logLevel DEBUG
    healthcheck:
      test: curl --fail -s http://localhost:1026/version || exit 1
    logging:
      driver: "json-file"
      options:
        max-size: "20M"
        max-file: "2"
  quantumleap:
    container_name: impetus-fiware-quantumleap
    image: orchestracities/quantumleap:edge
    ports:
      - "8668:8668"
    environment:      
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB_NAME=quantumleap
      - POSTGRES_DB_USER=postgres
      - POSTGRES_DB_PASS=1mp3tus4!
      - QL_CONFIG=/quantumleap.yaml
    networks:
      default:
        aliases:
          - quantumleap
    logging:
      driver: "json-file"
      options:
        max-size: "20M"
        max-file: "2"
    volumes:
      - ./quantumleap.yaml:/quantumleap.yaml

  platform:
    build: 
      context: ./AccessModule/
      dockerfile: Dockerfile
    container_name: impetus-accessmodule
    environment:
      - PG_USERNAME=postgres
      - PG_PASSWORD=1mp3tus4!
      - PG_HOSTNAME=postgres
      - PG_PORT=5432
      - PG_DATABASE=postgres
      - ORION_URL=http://orion:1026
      - FIWARE_FILES_PATH=/app/files
      - FIWARE_CONTEXT_PATH=/app/context
      - HOSTNAME=http://84.88.76.44/
      - QUANTUMLEAD_NOTIFY=http://quantumleap:8668/v2/notify
      - ORION_CONTEXT=http://accessmodule/context/impetus.json
    volumes:
      - ./files:/app/files
      - ./context:/app/context
    ports:
      - "80:80"
    networks:
      default:
        aliases:
          - accessmodule
    healthcheck:
      test: curl --fail -s http://localhost/ || exit 1
    logging:
      driver: "json-file"
      options:
        max-size: "50M"
        max-file: "18"
    depends_on:
      postgres:
        condition: service_healthy
volumes:
  mongo-db:
  crate-data:
  postgres-data:
